version: '3.8'

services:
  jenkins:
    image: custom-jenkins:2.463
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - /jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
